### ISSUE TITLE
requirements and IoU values 

### ISSUE THREAD

**Issue by mada99mj** [danfenghong/IEEE_TIP_UIU-Net#11]
i want to ask if there are any precise versions of the requirements (specially for torch, torchvision) because it didn't work for me without specifying it . I'm looking for a quick response please. and if you can help me with any information about the metrics because the way you coded  IoU and nIoU have a really small value0.000xx even if there is an intersection (visually noticed) . I tried to print the intersection to check, and it is = 0 and the comparison of the label and predicted mask shows the opposite (a good result).

**Comment by jothi9900** [comment]
Hi, i wanted to know if you were able to train the model successfully??

**Comment by mada99mj** [comment]
hi ,
 yes i trained it .

**Comment by HowCCB** [comment]
> hi , yes i trained it .

I had a trouble on training this model. Can you help me? The traceback are shown below.

Traceback (most recent call last):
  File "/home/liusr/UIUNET/train.py", line 120, in <module>
    for i, data in enumerate(salobj_dataloader):
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 517, in __next__
    data = self._next_data()
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1199, in _next_data
    return self._process_data(data)
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 1225, in _process_data
    data.reraise()
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/_utils.py", line 429, in reraise
    raise self.exc_type(msg)
RuntimeError: Caught RuntimeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/_utils/worker.py", line 202, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
    return self.collate_fn(data)
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 73, in default_collate
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 73, in <dictcomp>
    return {key: default_collate([d[key] for d in batch]) for key in elem}
  File "/home/liusr/anaconda3/envs/cvexp/lib/python3.9/site-packages/torch/utils/data/_utils/collate.py", line 55, in default_collate
    return torch.stack(batch, 0, out=out)
RuntimeError: result type Double can't be cast to the desired output type Byte
